import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    // High-level entry
    'intro',
    'getting-started',

    // Examples (explicit order)
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      link: { type: 'generated-index', title: 'Examples' },
      items: [
        'examples/plain',
        'examples/radix',
        'examples/mui',
      ],
    },

    // API (keep autogenerated under api/ to stay in sync with TypeDoc)
    {
      type: 'category',
      label: 'API',
      collapsed: true,
      link: { type: 'doc', id: 'api/index' },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;
